// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// Claims is an autogenerated mock type for the Claims type
type Claims struct {
	mock.Mock
}

type Claims_Expecter struct {
	mock *mock.Mock
}

func (_m *Claims) EXPECT() *Claims_Expecter {
	return &Claims_Expecter{mock: &_m.Mock}
}

// GetAudience provides a mock function with given fields:
func (_m *Claims) GetAudience() (jwt.ClaimStrings, error) {
	ret := _m.Called()

	var r0 jwt.ClaimStrings
	var r1 error
	if rf, ok := ret.Get(0).(func() (jwt.ClaimStrings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() jwt.ClaimStrings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.ClaimStrings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Claims_GetAudience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAudience'
type Claims_GetAudience_Call struct {
	*mock.Call
}

// GetAudience is a helper method to define mock.On call
func (_e *Claims_Expecter) GetAudience() *Claims_GetAudience_Call {
	return &Claims_GetAudience_Call{Call: _e.mock.On("GetAudience")}
}

func (_c *Claims_GetAudience_Call) Run(run func()) *Claims_GetAudience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Claims_GetAudience_Call) Return(_a0 jwt.ClaimStrings, _a1 error) *Claims_GetAudience_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Claims_GetAudience_Call) RunAndReturn(run func() (jwt.ClaimStrings, error)) *Claims_GetAudience_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpirationTime provides a mock function with given fields:
func (_m *Claims) GetExpirationTime() (*jwt.NumericDate, error) {
	ret := _m.Called()

	var r0 *jwt.NumericDate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Claims_GetExpirationTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpirationTime'
type Claims_GetExpirationTime_Call struct {
	*mock.Call
}

// GetExpirationTime is a helper method to define mock.On call
func (_e *Claims_Expecter) GetExpirationTime() *Claims_GetExpirationTime_Call {
	return &Claims_GetExpirationTime_Call{Call: _e.mock.On("GetExpirationTime")}
}

func (_c *Claims_GetExpirationTime_Call) Run(run func()) *Claims_GetExpirationTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Claims_GetExpirationTime_Call) Return(_a0 *jwt.NumericDate, _a1 error) *Claims_GetExpirationTime_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Claims_GetExpirationTime_Call) RunAndReturn(run func() (*jwt.NumericDate, error)) *Claims_GetExpirationTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuedAt provides a mock function with given fields:
func (_m *Claims) GetIssuedAt() (*jwt.NumericDate, error) {
	ret := _m.Called()

	var r0 *jwt.NumericDate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Claims_GetIssuedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuedAt'
type Claims_GetIssuedAt_Call struct {
	*mock.Call
}

// GetIssuedAt is a helper method to define mock.On call
func (_e *Claims_Expecter) GetIssuedAt() *Claims_GetIssuedAt_Call {
	return &Claims_GetIssuedAt_Call{Call: _e.mock.On("GetIssuedAt")}
}

func (_c *Claims_GetIssuedAt_Call) Run(run func()) *Claims_GetIssuedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Claims_GetIssuedAt_Call) Return(_a0 *jwt.NumericDate, _a1 error) *Claims_GetIssuedAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Claims_GetIssuedAt_Call) RunAndReturn(run func() (*jwt.NumericDate, error)) *Claims_GetIssuedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuer provides a mock function with given fields:
func (_m *Claims) GetIssuer() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Claims_GetIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuer'
type Claims_GetIssuer_Call struct {
	*mock.Call
}

// GetIssuer is a helper method to define mock.On call
func (_e *Claims_Expecter) GetIssuer() *Claims_GetIssuer_Call {
	return &Claims_GetIssuer_Call{Call: _e.mock.On("GetIssuer")}
}

func (_c *Claims_GetIssuer_Call) Run(run func()) *Claims_GetIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Claims_GetIssuer_Call) Return(_a0 string, _a1 error) *Claims_GetIssuer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Claims_GetIssuer_Call) RunAndReturn(run func() (string, error)) *Claims_GetIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotBefore provides a mock function with given fields:
func (_m *Claims) GetNotBefore() (*jwt.NumericDate, error) {
	ret := _m.Called()

	var r0 *jwt.NumericDate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Claims_GetNotBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotBefore'
type Claims_GetNotBefore_Call struct {
	*mock.Call
}

// GetNotBefore is a helper method to define mock.On call
func (_e *Claims_Expecter) GetNotBefore() *Claims_GetNotBefore_Call {
	return &Claims_GetNotBefore_Call{Call: _e.mock.On("GetNotBefore")}
}

func (_c *Claims_GetNotBefore_Call) Run(run func()) *Claims_GetNotBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Claims_GetNotBefore_Call) Return(_a0 *jwt.NumericDate, _a1 error) *Claims_GetNotBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Claims_GetNotBefore_Call) RunAndReturn(run func() (*jwt.NumericDate, error)) *Claims_GetNotBefore_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubject provides a mock function with given fields:
func (_m *Claims) GetSubject() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Claims_GetSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubject'
type Claims_GetSubject_Call struct {
	*mock.Call
}

// GetSubject is a helper method to define mock.On call
func (_e *Claims_Expecter) GetSubject() *Claims_GetSubject_Call {
	return &Claims_GetSubject_Call{Call: _e.mock.On("GetSubject")}
}

func (_c *Claims_GetSubject_Call) Run(run func()) *Claims_GetSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Claims_GetSubject_Call) Return(_a0 string, _a1 error) *Claims_GetSubject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Claims_GetSubject_Call) RunAndReturn(run func() (string, error)) *Claims_GetSubject_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaims creates a new instance of Claims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *Claims {
	mock := &Claims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
