run:
  timeout: 10m
  tests: false
linters:
  enable:
    - gofmt
    - goimports
    - misspell
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
  - SA1019 # temporarily ignore deprecation warnings
