version: 1

project_name: argocd-agent

before:
  hooks:
    - go mod tidy
    - ./hack/test.sh

builds:
  - id: agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    binary: argocd-agent-agent
    ldflags: "-extldflags=-static -X github.com/argoproj-labs/argocd-agent/internal/version.version={{.Version}}"
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    main: './cmd/agent/main.go'
  - id: principal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    binary: argocd-agent-principal
    ldflags: "-extldflags=-static -X github.com/argoproj-labs/argocd-agent/internal/version.version={{.Version}}"
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    main: './cmd/principal/main.go'


archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
