version: 2

project_name: argocd-agent

before:
  hooks:
    - go mod tidy

builds:
  - id: argocd-agentctl
    main: ./cmd/ctl
    binary: argocd-agentctl-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -extldflags="-static"
      - -X github.com/argoproj-labs/argocd-agent/internal/version.version={{ .Version }}
      - -X github.com/argoproj-labs/argocd-agent/internal/version.gitRevision={{ .FullCommit }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [binary]
    ids:
      - argocd-agentctl
    name_template: |-
      {{ .ProjectName }}ctl-{{ .Os }}-{{ .Arch }}

release:
  make_latest: "{{ .Env.GORELEASER_MAKE_LATEST }}"
  header: |
    {{ .Env.CHANGELOG_CONTENT }}

changelog:
  disable: true
