with-expecter: true
all: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/argoproj-labs/argocd-agent/internal/auth:
  github.com/argoproj-labs/argocd-agent/internal/queue:
  github.com/argoproj-labs/argocd-agent/internal/issuer:
  github.com/argoproj-labs/argocd-agent/internal/backend:
  k8s.io/client-go/util/workqueue:
    config:
      dir: "test/mocks/k8s-workqueue"
      all: false
    interfaces:
      TypedRateLimitingInterface:
