FROM docker.io/library/golang:1.22 AS builder
WORKDIR /src
COPY . .
RUN make agent
	
FROM docker.io/library/alpine:latest

COPY --from=builder /src/dist/argocd-agent-agent /bin/argocd-agent-agent

ENTRYPOINT ["/bin/argocd-agent-agent"]
