FROM docker.io/library/golang:1.23 AS builder
WORKDIR /src
COPY . .
RUN make principal
	
FROM docker.io/library/alpine:latest

COPY --from=builder /src/dist/argocd-agent-principal /bin/argocd-agent-principal
USER 999
ENTRYPOINT ["/bin/argocd-agent-principal"]
