site_name: argocd-agent
repo_url: https://github.com/argoproj-labs/argocd-agent
strict: true
theme: 
  name: material
  palette:
    primary: teal
  logo: assets/logo.png
  favicon: "assets/favicon.png"
  features:
  - content.code.copy
markdown_extensions: 
- codehilite
- admonition
- tables
- toc:
    permalink: true
    toc_depth: 3
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Overview: index.md
  - Features:
    - Overview: features/index.md
  - Concepts: 
    - Components & terminology: concepts/components-terminology.md
    - General architecture: concepts/architecture.md
    - Integration with Argo CD: concepts/argocd-integration.md
    - Agent modes:
      - Overview: concepts/agent-modes/index.md
      - Managed mode: concepts/agent-modes/managed.md
      - Autonomous mode: concepts/agent-modes/autonomous.md
    - Sync protocol: concepts/sync-protocol.md
  - Getting started:
    - Overview: getting-started/index.md
    - Kubernetes: getting-started/kubernetes/index.md
    - OpenShift: getting-started/openshift/index.md
    - OCM-io: getting-started/ocm-io/index.md
  - User guide:
    - Managing Applications: user-guide/applications.md
    - Managing AppProjects: user-guide/appprojects.md
    - Adding an agent: user-guide/adding-agents.md
    - Accessing live resources on workload clusters: user-guide/live-resources.md
  - Configuration:
    - Principal: 
        - Configuration parameters: configuration/principal/configuration.md
        - PKI: configuration/principal/pki-certificates.md
    - Agent:
        - Configuration parameters: configuration/agent/configuration.md
        - PKI: configuration/agent/pki-certificates.md
  - Operations:
    - Metrics: operations/metrics.md
    - Profiling: operations/profiling.md
  - Contributing:
    - Overview: contributing/index.md
    - Local development: contributing/local.md
    - Coding guidelines: contributing/code.md 
    - Documentation guidelines: contributing/docs.md 
    - Submitting PRs: contributing/prs.md
    - Code reviewing guide: contributing/review.md
  - FAQ: faq/index.md
