// Copyright 2024 The argocd-agent Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// argocd-agent-creds is a Kubernetes client-go exec credential plugin
// (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins).
//
// It is invoked by Argo CD (argocd-server, argocd-repo-server, etc., running
// on the argocd-agent principal cluster) whenever it builds a REST client
// for a cluster whose Argo CD Secret was generated by
// clusterprofile-integration-for-argocd from a ClusterProfile with an
// "argocd-agent" AccessProvider.
//
// It does not mint or store any secret itself: it only reads the
// non-expiring resource-proxy bearer token that clusterprofile-agent-driver
// already wrote into a companion Secret next to the ClusterProfile, and
// returns it to the caller as an ExecCredential.
//
// The binary must be present in the PATH of whichever Argo CD component
// invokes it. See docs/clusterprofile-integration/README.md for how it is
// injected into the argocd-server Pod via an init container.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	clientauthv1beta1 "k8s.io/client-go/pkg/apis/clientauthentication/v1beta1"
	"k8s.io/client-go/rest"

	"github.com/argoproj-labs/argocd-agent/internal/clusterprofiledriver"
)

const execInfoEnvVar = "KUBERNETES_EXEC_INFO"

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "argocd-agent-creds: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	raw := os.Getenv(execInfoEnvVar)
	if raw == "" {
		return fmt.Errorf("%s is not set; this binary must be invoked as a client-go exec credential plugin", execInfoEnvVar)
	}

	var execCred clientauthv1beta1.ExecCredential
	if err := json.Unmarshal([]byte(raw), &execCred); err != nil {
		return fmt.Errorf("failed to parse %s: %w", execInfoEnvVar, err)
	}

	// Primary channel: env vars advertised by clusterprofile-agent-driver via
	// the KEP-5339 additional-envs cluster extension (see
	// clusterprofiledriver.additionalEnvVarsExtensionKey). These are applied
	// to this process's environment unconditionally by client-go's exec
	// authenticator, regardless of whether Cluster/ProvideClusterInfo made it
	// through for this particular request - which empirically (Argo CD
	// v3.4.4) it does not for at least the API-discovery-client path used by
	// GetResource/live-manifest/pod-logs.
	agentName := os.Getenv(clusterprofiledriver.EnvAgentName)
	tokenSecretName := os.Getenv(clusterprofiledriver.EnvTokenSecretName)
	tokenSecretNamespace := os.Getenv(clusterprofiledriver.EnvTokenSecretNamespace)
	key := os.Getenv(clusterprofiledriver.EnvTokenSecretKey)
	mtlsSecretName := os.Getenv(clusterprofiledriver.EnvMTLSSecretName)
	mtlsSecretNamespace := os.Getenv(clusterprofiledriver.EnvMTLSSecretNamespace)

	// Fallback channel: ExecCredential.Spec.Cluster.Config, populated from
	// the "client.authentication.k8s.io/exec" cluster extension when Argo CD
	// does pass Cluster through (e.g. other call sites/future Argo CD
	// versions may behave differently).
	if tokenSecretName == "" || tokenSecretNamespace == "" {
		if execCred.Spec.Cluster == nil || len(execCred.Spec.Cluster.Config.Raw) == 0 {
			if os.Getenv("ARGOCD_AGENT_CREDS_DEBUG") != "" {
				fmt.Fprintf(os.Stderr, "argocd-agent-creds: DEBUG raw KUBERNETES_EXEC_INFO=%s\n", raw)
			}
			return fmt.Errorf("no token secret reference available: neither %s/%s env vars nor a cluster config extension were provided", clusterprofiledriver.EnvTokenSecretName, clusterprofiledriver.EnvTokenSecretNamespace)
		}
		var ext clusterprofiledriver.ExecExtension
		if err := json.Unmarshal(execCred.Spec.Cluster.Config.Raw, &ext); err != nil {
			return fmt.Errorf("failed to parse cluster config extension: %w", err)
		}
		agentName = ext.AgentName
		tokenSecretName = ext.TokenSecretName
		tokenSecretNamespace = ext.TokenSecretNamespace
		key = ext.TokenSecretKey
	}
	if key == "" {
		key = clusterprofiledriver.TokenSecretKey
	}
	// Fall back to the well-known shared mTLS secret name/namespace if the
	// driver didn't advertise one (e.g. an older driver version, or the
	// Cluster.Config-only fallback path above).
	if mtlsSecretName == "" {
		mtlsSecretName = clusterprofiledriver.SharedClientCertSecretName
	}
	if mtlsSecretNamespace == "" {
		mtlsSecretNamespace = tokenSecretNamespace
	}

	cfg, err := rest.InClusterConfig()
	if err != nil {
		return fmt.Errorf("failed to load in-cluster config: %w", err)
	}
	clientset, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		return fmt.Errorf("failed to build kubernetes client: %w", err)
	}
	ctx := context.Background()

	token, err := fetchSecretKey(ctx, clientset, tokenSecretNamespace, tokenSecretName, key)
	if err != nil {
		return fmt.Errorf("failed to fetch resource-proxy token for agent %q: %w", agentName, err)
	}

	// The resource proxy's TLS listener is hardcoded to
	// tls.RequireAndVerifyClientCert (argocd-agent's existing, unmodified
	// cmd/argocd-agent/principal.go). A bearer token alone cannot satisfy
	// the TLS handshake, so we also present a CA-signed client certificate;
	// see the comment on clusterprofiledriver.SharedClientCertSecretName for
	// why one shared cert works for every agent.
	certPEM, err := fetchSecretKey(ctx, clientset, mtlsSecretNamespace, mtlsSecretName, corev1.TLSCertKey)
	if err != nil {
		return fmt.Errorf("failed to fetch shared mTLS client certificate %s/%s: %w", mtlsSecretNamespace, mtlsSecretName, err)
	}
	keyPEM, err := fetchSecretKey(ctx, clientset, mtlsSecretNamespace, mtlsSecretName, corev1.TLSPrivateKeyKey)
	if err != nil {
		return fmt.Errorf("failed to fetch shared mTLS client key %s/%s: %w", mtlsSecretNamespace, mtlsSecretName, err)
	}

	resp := clientauthv1beta1.ExecCredential{
		TypeMeta: metav1.TypeMeta{
			APIVersion: clientauthv1beta1.SchemeGroupVersion.String(),
			Kind:       "ExecCredential",
		},
		Status: &clientauthv1beta1.ExecCredentialStatus{
			// Resource-proxy tokens minted by clusterprofile-agent-driver do
			// not expire, so no ExpirationTimestamp is set.
			Token:                 token,
			ClientCertificateData: certPEM,
			ClientKeyData:         keyPEM,
		},
	}

	out, err := json.Marshal(resp)
	if err != nil {
		return fmt.Errorf("failed to marshal ExecCredential response: %w", err)
	}
	fmt.Println(string(out))
	return nil
}

// fetchSecretKey reads a single data key from a Secret using this process's
// in-cluster ServiceAccount. The calling Argo CD component's ServiceAccount
// must have RBAC "get" permission on Secrets in the given namespace
// (typically the argocd namespace itself, if ClusterProfiles are co-located
// with the Argo CD control plane).
func fetchSecretKey(ctx context.Context, clientset *kubernetes.Clientset, namespace, name, key string) (string, error) {
	secret, err := clientset.CoreV1().Secrets(namespace).Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		return "", fmt.Errorf("failed to get secret %s/%s: %w", namespace, name, err)
	}

	data, ok := secret.Data[key]
	if !ok || len(data) == 0 {
		return "", fmt.Errorf("secret %s/%s has no data at key %q", namespace, name, key)
	}
	return string(data), nil
}
