// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	backend "github.com/argoproj-labs/argocd-agent/internal/backend"

	mock "github.com/stretchr/testify/mock"

	time "time"

	v1 "k8s.io/api/core/v1"
)

// GPGKey is an autogenerated mock type for the GPGKey type
type GPGKey struct {
	mock.Mock
}

type GPGKey_Expecter struct {
	mock *mock.Mock
}

func (_m *GPGKey) EXPECT() *GPGKey_Expecter {
	return &GPGKey_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cm
func (_m *GPGKey) Create(ctx context.Context, cm *v1.ConfigMap) (*v1.ConfigMap, error) {
	ret := _m.Called(ctx, cm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap) (*v1.ConfigMap, error)); ok {
		return rf(ctx, cm)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap) *v1.ConfigMap); ok {
		r0 = rf(ctx, cm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ConfigMap) error); ok {
		r1 = rf(ctx, cm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GPGKey_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type GPGKey_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cm *v1.ConfigMap
func (_e *GPGKey_Expecter) Create(ctx interface{}, cm interface{}) *GPGKey_Create_Call {
	return &GPGKey_Create_Call{Call: _e.mock.On("Create", ctx, cm)}
}

func (_c *GPGKey_Create_Call) Run(run func(ctx context.Context, cm *v1.ConfigMap)) *GPGKey_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.ConfigMap))
	})
	return _c
}

func (_c *GPGKey_Create_Call) Return(_a0 *v1.ConfigMap, _a1 error) *GPGKey_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GPGKey_Create_Call) RunAndReturn(run func(context.Context, *v1.ConfigMap) (*v1.ConfigMap, error)) *GPGKey_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, namespace, deletionPropagation
func (_m *GPGKey) Delete(ctx context.Context, name string, namespace string, deletionPropagation *backend.DeletionPropagation) error {
	ret := _m.Called(ctx, name, namespace, deletionPropagation)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *backend.DeletionPropagation) error); ok {
		r0 = rf(ctx, name, namespace, deletionPropagation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GPGKey_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type GPGKey_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
//   - deletionPropagation *backend.DeletionPropagation
func (_e *GPGKey_Expecter) Delete(ctx interface{}, name interface{}, namespace interface{}, deletionPropagation interface{}) *GPGKey_Delete_Call {
	return &GPGKey_Delete_Call{Call: _e.mock.On("Delete", ctx, name, namespace, deletionPropagation)}
}

func (_c *GPGKey_Delete_Call) Run(run func(ctx context.Context, name string, namespace string, deletionPropagation *backend.DeletionPropagation)) *GPGKey_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*backend.DeletionPropagation))
	})
	return _c
}

func (_c *GPGKey_Delete_Call) Return(_a0 error) *GPGKey_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GPGKey_Delete_Call) RunAndReturn(run func(context.Context, string, string, *backend.DeletionPropagation) error) *GPGKey_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSynced provides a mock function with given fields: duration
func (_m *GPGKey) EnsureSynced(duration time.Duration) error {
	ret := _m.Called(duration)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSynced")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = rf(duration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GPGKey_EnsureSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSynced'
type GPGKey_EnsureSynced_Call struct {
	*mock.Call
}

// EnsureSynced is a helper method to define mock.On call
//   - duration time.Duration
func (_e *GPGKey_Expecter) EnsureSynced(duration interface{}) *GPGKey_EnsureSynced_Call {
	return &GPGKey_EnsureSynced_Call{Call: _e.mock.On("EnsureSynced", duration)}
}

func (_c *GPGKey_EnsureSynced_Call) Run(run func(duration time.Duration)) *GPGKey_EnsureSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *GPGKey_EnsureSynced_Call) Return(_a0 error) *GPGKey_EnsureSynced_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GPGKey_EnsureSynced_Call) RunAndReturn(run func(time.Duration) error) *GPGKey_EnsureSynced_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, namespace
func (_m *GPGKey) Get(ctx context.Context, name string, namespace string) (*v1.ConfigMap, error) {
	ret := _m.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1.ConfigMap, error)); ok {
		return rf(ctx, name, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.ConfigMap); ok {
		r0 = rf(ctx, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GPGKey_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GPGKey_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *GPGKey_Expecter) Get(ctx interface{}, name interface{}, namespace interface{}) *GPGKey_Get_Call {
	return &GPGKey_Get_Call{Call: _e.mock.On("Get", ctx, name, namespace)}
}

func (_c *GPGKey_Get_Call) Run(run func(ctx context.Context, name string, namespace string)) *GPGKey_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *GPGKey_Get_Call) Return(_a0 *v1.ConfigMap, _a1 error) *GPGKey_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GPGKey_Get_Call) RunAndReturn(run func(context.Context, string, string) (*v1.ConfigMap, error)) *GPGKey_Get_Call {
	_c.Call.Return(run)
	return _c
}

// StartInformer provides a mock function with given fields: ctx
func (_m *GPGKey) StartInformer(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartInformer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GPGKey_StartInformer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartInformer'
type GPGKey_StartInformer_Call struct {
	*mock.Call
}

// StartInformer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GPGKey_Expecter) StartInformer(ctx interface{}) *GPGKey_StartInformer_Call {
	return &GPGKey_StartInformer_Call{Call: _e.mock.On("StartInformer", ctx)}
}

func (_c *GPGKey_StartInformer_Call) Run(run func(ctx context.Context)) *GPGKey_StartInformer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GPGKey_StartInformer_Call) Return(_a0 error) *GPGKey_StartInformer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GPGKey_StartInformer_Call) RunAndReturn(run func(context.Context) error) *GPGKey_StartInformer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, cm
func (_m *GPGKey) Update(ctx context.Context, cm *v1.ConfigMap) (*v1.ConfigMap, error) {
	ret := _m.Called(ctx, cm)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap) (*v1.ConfigMap, error)); ok {
		return rf(ctx, cm)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap) *v1.ConfigMap); ok {
		r0 = rf(ctx, cm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ConfigMap) error); ok {
		r1 = rf(ctx, cm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GPGKey_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GPGKey_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cm *v1.ConfigMap
func (_e *GPGKey_Expecter) Update(ctx interface{}, cm interface{}) *GPGKey_Update_Call {
	return &GPGKey_Update_Call{Call: _e.mock.On("Update", ctx, cm)}
}

func (_c *GPGKey_Update_Call) Run(run func(ctx context.Context, cm *v1.ConfigMap)) *GPGKey_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.ConfigMap))
	})
	return _c
}

func (_c *GPGKey_Update_Call) Return(_a0 *v1.ConfigMap, _a1 error) *GPGKey_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GPGKey_Update_Call) RunAndReturn(run func(context.Context, *v1.ConfigMap) (*v1.ConfigMap, error)) *GPGKey_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewGPGKey creates a new instance of GPGKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGPGKey(t interface {
	mock.TestingT
	Cleanup(func())
}) *GPGKey {
	mock := &GPGKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
