apiVersion: v1
kind: Service
metadata:
  name: rathole-container-external
spec:
  selector:
    app: rathole-container
  # type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: "2333"
      port: 2333 # The port the service listens on inside the cluster
      targetPort: 2333 # The port your application is listening on in the pod
#      nodePort: 30000 # The static port exposed on each node (optional, Kubernetes assigns if omitted)
