# This is the default any-uid OpenShift SCC, but with:
# - .allowedCapabilities[0] = "NET_BIND_SERVICE"
# - .seccompProfiles[0] = "runtime/default"

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1

metadata:
  annotations:
    kubernetes.io/description: >-
      anyuid provides all features of the restricted SCC but allows users to run
      with any UID and any GID.
  name: anyuid-seccomp-netbind

seccompProfiles:
  - runtime/default
allowedCapabilities:
  - NET_BIND_SERVICE
fsGroup:
  type: RunAsAny
groups:
  - 'system:cluster-admins'
priority: 10
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
  - configMap
  - csi
  - downwardAPI
  - emptyDir
  - ephemeral
  - persistentVolumeClaim
  - projected
  - secret

defaultAddCapabilities: null

readOnlyRootFilesystem: false

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
