apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-agent-cr-examples
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-agent-cr-examples
subjects:
- kind: ServiceAccount
  name: argocd-agent-agent
  namespace: default  # Replace with the namespace the agent is in
