resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=stable

patches:
# Get rid of everything related to the API server
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-server
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-server
- patch: |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: argocd-server-network-policy
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: argocd-server
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argocd-server
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argocd-server
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: argocd-server
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: argocd-server

# Get rid of everything related to Dex
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-dex-server
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-dex-server
- patch: |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: argocd-dex-server-network-policy
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: argocd-dex-server
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argocd-dex-server
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argocd-dex-server

# Get rid of everything related to notifications controller
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-notifications-controller
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-notifications-controller-metrics
- patch: |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: argocd-notifications-controller-network-policy
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: argocd-notifications-controller
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argocd-notifications-controller
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argocd-notifications-controller
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-notifications-secret

