{{- if .Values.secrets.jwt.create }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: argocd-agent-jwt
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
  {{- with include "argocd-agent-principal.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  jwt.key: {{ .Values.secrets.jwt.key | quote }}
{{- end }}