{{- if .Values.secrets.userpass.create }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "argocd-agent-principal.userpassSecretName" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
  {{- with include "argocd-agent-principal.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  passwd: {{ .Values.secrets.userpass.passwd | quote }}
{{- end }}