{{- if .Values.secrets.server.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: argocd-agent-principal-tls
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
  {{- with include "argocd-agent-principal.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.server.tls.crt | quote }}
  tls.key: {{ .Values.secrets.server.tls.key | quote }}
{{- end }}