apiVersion: v2
name: argocd-agent-principal
description: Argo CD Agent Principal component for multi-cluster application management
type: application
version: 0.3.3
appVersion: "v0.8.1"
home: https://github.com/argoproj-labs/argocd-agent
sources:
  - https://github.com/argoproj-labs/argocd-agent
keywords:
  - argocd
  - gitops
  - agent
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Argo Project Maintainers
    url: https://github.com/argoproj-labs/argocd-agent
annotations:
  charts.openshift.io/name: "Argo CD Agent - Principal Component"
