apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: argocd-agent-auto
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    description: argocd-agent-auto is an OCM-io for ArgoCD agent autonomous mode
    displayName: ArgoCD Agent Autonomous
  supportedConfigs:
    - group: addon.open-cluster-management.io
      resource: addontemplates
      defaultConfig:
        name: argocd-agent-auto-template
