apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-agent-agent
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-agent-agent
    app.kubernetes.io/part-of: argocd-agent
    app.kubernetes.io/component: agent
spec:
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-agent-agent
