apiVersion: v1
kind: Service
metadata:
  labels:
      app.kubernetes.io/name: argocd-agent-agent
      app.kubernetes.io/part-of: argocd-agent
      app.kubernetes.io/component: agent
  name: argocd-agent-agent-healthz
spec:
  ports:
    - name: healthz
      protocol: TCP
      port: 8002
      targetPort: 8002
  selector:
    app.kubernetes.io/name: argocd-agent-agent 