apiVersion: v1
kind: Service
metadata:
  labels:
      app.kubernetes.io/name: argocd-agent-agent
      app.kubernetes.io/part-of: argocd-agent
      app.kubernetes.io/component: agent
  name: {{ include "argocd-agent-agent.healthzServiceName" . }}
  namespace: {{ include  "argocd-agent-agent.namespace" . }}
  {{- with .Values.service.healthz.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ports:
    - name: healthz
      protocol: TCP
      port: {{ .Values.service.healthz.port }}
      targetPort: {{ .Values.service.healthz.targetPort }}
  selector:
    app.kubernetes.io/name: argocd-agent-agent 