apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-agent-params
  namespace: {{ include  "argocd-agent-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: argocd-agent-agent
    app.kubernetes.io/part-of: argocd-agent
    app.kubernetes.io/component: agent 
data:
  # agent.mode: The mode this agent should operate in. Valid values are
  # "autonomous" or "managed".
  # Default: "autonomous"
  agent.mode: {{ .Values.agentMode }}
  # agent.creds: Valid credential identifier for this agent. Must be in the
  # format <method>:<configuration>. Valid values are:
  # - "userpass:_path_to_encrypted_creds_" where _path_to_encrypted_creds_ is
  #   the path to the file containing encrypted credential for authenticatiion.
  # - "mtls:_agent_id_regex_" where _agent_id_regex_ is the regex pattern for
  #   extracting the agent ID from client cert subject.
  # Default: ""
  agent.creds: {{ .Values.auth }}
  # agent.tls.secret-name: Name of the secret containing the TLS certificate.
  # Default: "argocd-agent-client-tls"
  agent.tls.secret-name: {{ .Values.tlsSecretName | quote }}
  # agent.tls.root-ca-secret-name: Name of the secret containing the root CA certificate.
  # Default: "argocd-agent-principal-ca"
  agent.tls.root-ca-secret-name: {{ .Values.tlsRootCASecretName | quote }}
  # agent.tls.client.insecure: Whether to skip the validation of the remote TLS
  # credentials. Insecure. Do only use for development purposes.
  # Default: false
  agent.tls.client.insecure: {{ .Values.tlsClientInSecure  | quote }}
  # agent.tls.root-ca-path: The path to a file containing the certificates for
  # the TLS root certificate authority used to validate the remote principal. 
  # Default: ""
  agent.tls.root-ca-path: {{ .Values.tlsRootCAPath }}
  # agent.tls.client.cert-path: Path to a file containing the agent's TLS client
  # certificate.
  # Default: ""
  agent.tls.client.cert-path: {{ .Values.tlsClientCertPath }}
  # agent.tls.client.cert-path: Path to a file containing the agent's TLS client
  # private key.
  # Default: ""
  agent.tls.client.key-path: {{ .Values.tlsClientKeyPath }}
  # agent.log.level: The log level the agent should use. Valid values are
  # trace, debug, info, warn and error.
  # Default: "info"
  agent.log.level: {{ .Values.logLevel }}
  # agent.namespace: The namespace the agent should operate and manage the
  # Argo CD resources in.
  # Default: "argocd"
  agent.namespace: {{ include  "argocd-agent-agent.namespace" . }} 
  # agent.principal.address: The remote address of the principal to connect
  # to. Can be a DNS name, an IPv4 address or an IPv6 address.
  # Default: ""
  agent.server.address: {{ .Values.server}}
  # agent.server.port: The remote port of the principal to connect to.
  # Default: "443"
  agent.server.port: {{ .Values.serverPort | quote }}
  # agent.metrics.port: The port the metrics server should listen on.
  # Default: 8181
  agent.metrics.port: {{ .Values.metricsPort | quote }}
  # agent.healthz.port: The port the health check server should listen on.
  # Default: 8002
  agent.healthz.port: {{ .Values.healthzPort | quote }}
  # agent.redis.address: The address of the Redis server.
  # Default: "argocd-redis:6379"
  agent.redis.address: {{ .Values.redisAddress | quote }}
  # agent.redis.username: The username for Redis authentication.
  # Default: ""
  agent.redis.username: {{ .Values.redisUsername | quote }}
  # agent.keep-alive.interval: The keep-alive interval for connections
  # Default: "30s"
  agent.keep-alive.interval: {{ .Values.keepAliveInterval | quote }}
  # agent.log.format: The log format for the agent (text or json).
  # Default: "text"
  agent.log.format: {{ .Values.logFormat | quote }}
  # agent.websocket.enabled: Whether to enable WebSocket connections.
  # Default: false
  agent.websocket.enabled: {{ .Values.enableWebSocket | quote }}
  # agent.compression.enabled: Whether to enable gRPC compression.
  # Default: false
  agent.compression.enabled: {{ .Values.enableCompression | quote }}
  # agent.pprof.port: Port for pprof server (0 disables pprof).
  # Default: 0
  agent.pprof.port: {{ .Values.pprofPort | quote }}
  # agent.resource-proxy.enabled: Whether to enable resource proxy.
  # Default: true
  agent.resource-proxy.enabled: {{ .Values.enableResourceProxy | quote }}
  # agent.cache.refresh-interval: Cache refresh interval.
  # Default: "10s"
  agent.cache.refresh-interval: {{ .Values.cacheRefreshInterval | quote }}
