apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: argocd-agent-agent
    app.kubernetes.io/part-of: argocd-agent
    app.kubernetes.io/component: agent
  name: argocd-agent-agent
  namespace: {{ include  "argocd-agent-agent.namespace" . }}