apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argocd-agent-agent.roleName" . }}
  namespace: {{ include "argocd-agent-agent.namespace" . }}
  labels:
    {{- include "argocd-agent-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  - applicationsets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list