apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-agent-agent.healthzServiceName" . }}
  namespace: {{ include "argocd-agent-agent.namespace" . }}
  labels:
    {{- include "argocd-agent-agent.labels" . | nindent 4 }}
  {{- with .Values.service.healthz.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: healthz
      protocol: TCP
      port: {{ .Values.service.healthz.port }}
      targetPort: {{ .Values.service.healthz.targetPort }}
  selector:
    {{- include "argocd-agent-agent.selectorLabels" . | nindent 4 }}