apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-agent-principal.fullname" . }}-metrics
  namespace: {{ include "argocd-agent-principal.namespace" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - port: {{ .Values.metricsService.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "argocd-agent-principal.selectorLabels" . | nindent 4 }} 