apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-agent-principal.fullname" . }}
  namespace: {{ include "argocd-agent-principal.namespace" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: principal
      protocol: TCP
      name: principal
  selector:
    {{- include "argocd-agent-principal.selectorLabels" . | nindent 4 }} 