// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: replication.proto

package replicationapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	// Subscribe establishes a bidirectional stream for replication.
	// The replica sends ACKs and receives replicated events.
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (Replication_SubscribeClient, error)
	// GetSnapshot returns the current state snapshot for initial sync
	GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*ReplicationSnapshot, error)
	// Status returns the current replication status
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*ReplicationStatus, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (Replication_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[0], "/replicationapi.Replication/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationSubscribeClient{stream}
	return x, nil
}

type Replication_SubscribeClient interface {
	Send(*ReplicationAck) error
	Recv() (*ReplicatedEvent, error)
	grpc.ClientStream
}

type replicationSubscribeClient struct {
	grpc.ClientStream
}

func (x *replicationSubscribeClient) Send(m *ReplicationAck) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicationSubscribeClient) Recv() (*ReplicatedEvent, error) {
	m := new(ReplicatedEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicationClient) GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*ReplicationSnapshot, error) {
	out := new(ReplicationSnapshot)
	err := c.cc.Invoke(ctx, "/replicationapi.Replication/GetSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*ReplicationStatus, error) {
	out := new(ReplicationStatus)
	err := c.cc.Invoke(ctx, "/replicationapi.Replication/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility
type ReplicationServer interface {
	// Subscribe establishes a bidirectional stream for replication.
	// The replica sends ACKs and receives replicated events.
	Subscribe(Replication_SubscribeServer) error
	// GetSnapshot returns the current state snapshot for initial sync
	GetSnapshot(context.Context, *SnapshotRequest) (*ReplicationSnapshot, error)
	// Status returns the current replication status
	Status(context.Context, *StatusRequest) (*ReplicationStatus, error)
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have forward compatible implementations.
type UnimplementedReplicationServer struct {
}

func (UnimplementedReplicationServer) Subscribe(Replication_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedReplicationServer) GetSnapshot(context.Context, *SnapshotRequest) (*ReplicationSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedReplicationServer) Status(context.Context, *StatusRequest) (*ReplicationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).Subscribe(&replicationSubscribeServer{stream})
}

type Replication_SubscribeServer interface {
	Send(*ReplicatedEvent) error
	Recv() (*ReplicationAck, error)
	grpc.ServerStream
}

type replicationSubscribeServer struct {
	grpc.ServerStream
}

func (x *replicationSubscribeServer) Send(m *ReplicatedEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicationSubscribeServer) Recv() (*ReplicationAck, error) {
	m := new(ReplicationAck)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Replication_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicationapi.Replication/GetSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).GetSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicationapi.Replication/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replicationapi.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _Replication_GetSnapshot_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Replication_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Replication_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "replication.proto",
}
