// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: terminalstream.proto

package terminalstreamapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TerminalStreamServiceClient is the client API for TerminalStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TerminalStreamServiceClient interface {
	// StreamTerminal establishes a bidirectional stream for a web terminal session.
	// The client (agent) sends stdin data and receives stdout/stderr data.
	// The server (principal) receives stdin from the browser and sends stdout/stderr back.
	StreamTerminal(ctx context.Context, opts ...grpc.CallOption) (TerminalStreamService_StreamTerminalClient, error)
}

type terminalStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerminalStreamServiceClient(cc grpc.ClientConnInterface) TerminalStreamServiceClient {
	return &terminalStreamServiceClient{cc}
}

func (c *terminalStreamServiceClient) StreamTerminal(ctx context.Context, opts ...grpc.CallOption) (TerminalStreamService_StreamTerminalClient, error) {
	stream, err := c.cc.NewStream(ctx, &TerminalStreamService_ServiceDesc.Streams[0], "/terminalstreamapi.TerminalStreamService/StreamTerminal", opts...)
	if err != nil {
		return nil, err
	}
	x := &terminalStreamServiceStreamTerminalClient{stream}
	return x, nil
}

type TerminalStreamService_StreamTerminalClient interface {
	Send(*TerminalStreamData) error
	Recv() (*TerminalStreamData, error)
	grpc.ClientStream
}

type terminalStreamServiceStreamTerminalClient struct {
	grpc.ClientStream
}

func (x *terminalStreamServiceStreamTerminalClient) Send(m *TerminalStreamData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *terminalStreamServiceStreamTerminalClient) Recv() (*TerminalStreamData, error) {
	m := new(TerminalStreamData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TerminalStreamServiceServer is the server API for TerminalStreamService service.
// All implementations must embed UnimplementedTerminalStreamServiceServer
// for forward compatibility
type TerminalStreamServiceServer interface {
	// StreamTerminal establishes a bidirectional stream for a web terminal session.
	// The client (agent) sends stdin data and receives stdout/stderr data.
	// The server (principal) receives stdin from the browser and sends stdout/stderr back.
	StreamTerminal(TerminalStreamService_StreamTerminalServer) error
	mustEmbedUnimplementedTerminalStreamServiceServer()
}

// UnimplementedTerminalStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTerminalStreamServiceServer struct {
}

func (UnimplementedTerminalStreamServiceServer) StreamTerminal(TerminalStreamService_StreamTerminalServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTerminal not implemented")
}
func (UnimplementedTerminalStreamServiceServer) mustEmbedUnimplementedTerminalStreamServiceServer() {}

// UnsafeTerminalStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerminalStreamServiceServer will
// result in compilation errors.
type UnsafeTerminalStreamServiceServer interface {
	mustEmbedUnimplementedTerminalStreamServiceServer()
}

func RegisterTerminalStreamServiceServer(s grpc.ServiceRegistrar, srv TerminalStreamServiceServer) {
	s.RegisterService(&TerminalStreamService_ServiceDesc, srv)
}

func _TerminalStreamService_StreamTerminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TerminalStreamServiceServer).StreamTerminal(&terminalStreamServiceStreamTerminalServer{stream})
}

type TerminalStreamService_StreamTerminalServer interface {
	Send(*TerminalStreamData) error
	Recv() (*TerminalStreamData, error)
	grpc.ServerStream
}

type terminalStreamServiceStreamTerminalServer struct {
	grpc.ServerStream
}

func (x *terminalStreamServiceStreamTerminalServer) Send(m *TerminalStreamData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *terminalStreamServiceStreamTerminalServer) Recv() (*TerminalStreamData, error) {
	m := new(TerminalStreamData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TerminalStreamService_ServiceDesc is the grpc.ServiceDesc for TerminalStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerminalStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terminalstreamapi.TerminalStreamService",
	HandlerType: (*TerminalStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTerminal",
			Handler:       _TerminalStreamService_StreamTerminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "terminalstream.proto",
}
