apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agent-allow-redis-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-agent-agent
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-redis
    ports:
    - port: 6379
      protocol: TCP

