// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: haadmin.proto

package haadminapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HAAdminClient is the client API for HAAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HAAdminClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*HAStatusResponse, error)
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	Demote(ctx context.Context, in *DemoteRequest, opts ...grpc.CallOption) (*DemoteResponse, error)
}

type hAAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewHAAdminClient(cc grpc.ClientConnInterface) HAAdminClient {
	return &hAAdminClient{cc}
}

func (c *hAAdminClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*HAStatusResponse, error) {
	out := new(HAStatusResponse)
	err := c.cc.Invoke(ctx, "/haadminapi.HAAdmin/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hAAdminClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, "/haadminapi.HAAdmin/Promote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hAAdminClient) Demote(ctx context.Context, in *DemoteRequest, opts ...grpc.CallOption) (*DemoteResponse, error) {
	out := new(DemoteResponse)
	err := c.cc.Invoke(ctx, "/haadminapi.HAAdmin/Demote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HAAdminServer is the server API for HAAdmin service.
// All implementations must embed UnimplementedHAAdminServer
// for forward compatibility
type HAAdminServer interface {
	Status(context.Context, *StatusRequest) (*HAStatusResponse, error)
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	Demote(context.Context, *DemoteRequest) (*DemoteResponse, error)
	mustEmbedUnimplementedHAAdminServer()
}

// UnimplementedHAAdminServer must be embedded to have forward compatible implementations.
type UnimplementedHAAdminServer struct {
}

func (UnimplementedHAAdminServer) Status(context.Context, *StatusRequest) (*HAStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedHAAdminServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedHAAdminServer) Demote(context.Context, *DemoteRequest) (*DemoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Demote not implemented")
}
func (UnimplementedHAAdminServer) mustEmbedUnimplementedHAAdminServer() {}

// UnsafeHAAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HAAdminServer will
// result in compilation errors.
type UnsafeHAAdminServer interface {
	mustEmbedUnimplementedHAAdminServer()
}

func RegisterHAAdminServer(s grpc.ServiceRegistrar, srv HAAdminServer) {
	s.RegisterService(&HAAdmin_ServiceDesc, srv)
}

func _HAAdmin_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAAdminServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/haadminapi.HAAdmin/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAAdminServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HAAdmin_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAAdminServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/haadminapi.HAAdmin/Promote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAAdminServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HAAdmin_Demote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAAdminServer).Demote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/haadminapi.HAAdmin/Demote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAAdminServer).Demote(ctx, req.(*DemoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HAAdmin_ServiceDesc is the grpc.ServiceDesc for HAAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HAAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "haadminapi.HAAdmin",
	HandlerType: (*HAAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _HAAdmin_Status_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _HAAdmin_Promote_Handler,
		},
		{
			MethodName: "Demote",
			Handler:    _HAAdmin_Demote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "haadmin.proto",
}
