// Copyright 2024 The argocd-agent Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: haadmin.proto

package haadminapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HAStatusResponse contains the current HA state of the principal
type HAStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State              string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	PreferredRole      string `protobuf:"bytes,2,opt,name=preferred_role,json=preferredRole,proto3" json:"preferred_role,omitempty"`
	PeerAddress        string `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	PeerReachable      bool   `protobuf:"varint,4,opt,name=peer_reachable,json=peerReachable,proto3" json:"peer_reachable,omitempty"`
	PeerState          string `protobuf:"bytes,5,opt,name=peer_state,json=peerState,proto3" json:"peer_state,omitempty"`
	ConnectedReplicas  int32  `protobuf:"varint,6,opt,name=connected_replicas,json=connectedReplicas,proto3" json:"connected_replicas,omitempty"`
	LastEventTimestamp int64  `protobuf:"varint,7,opt,name=last_event_timestamp,json=lastEventTimestamp,proto3" json:"last_event_timestamp,omitempty"`
	LastSequenceNum    uint64 `protobuf:"varint,8,opt,name=last_sequence_num,json=lastSequenceNum,proto3" json:"last_sequence_num,omitempty"`
	ConnectedAgents    int32  `protobuf:"varint,9,opt,name=connected_agents,json=connectedAgents,proto3" json:"connected_agents,omitempty"`
}

func (x *HAStatusResponse) Reset() {
	*x = HAStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_haadmin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HAStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HAStatusResponse) ProtoMessage() {}

func (x *HAStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_haadmin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HAStatusResponse.ProtoReflect.Descriptor instead.
func (*HAStatusResponse) Descriptor() ([]byte, []int) {
	return file_haadmin_proto_rawDescGZIP(), []int{0}
}

func (x *HAStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HAStatusResponse) GetPreferredRole() string {
	if x != nil {
		return x.PreferredRole
	}
	return ""
}

func (x *HAStatusResponse) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *HAStatusResponse) GetPeerReachable() bool {
	if x != nil {
		return x.PeerReachable
	}
	return false
}

func (x *HAStatusResponse) GetPeerState() string {
	if x != nil {
		return x.PeerState
	}
	return ""
}

func (x *HAStatusResponse) GetConnectedReplicas() int32 {
	if x != nil {
		return x.ConnectedReplicas
	}
	return 0
}

func (x *HAStatusResponse) GetLastEventTimestamp() int64 {
	if x != nil {
		return x.LastEventTimestamp
	}
	return 0
}

func (x *HAStatusResponse) GetLastSequenceNum() uint64 {
	if x != nil {
		return x.LastSequenceNum
	}
	return 0
}

func (x *HAStatusResponse) GetConnectedAgents() int32 {
	if x != nil {
		return x.ConnectedAgents
	}
	return 0
}

// PromoteRequest asks the principal to become ACTIVE
type PromoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *PromoteRequest) Reset() {
	*x = PromoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_haadmin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRequest) ProtoMessage() {}

func (x *PromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_haadmin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRequest.ProtoReflect.Descriptor instead.
func (*PromoteRequest) Descriptor() ([]byte, []int) {
	return file_haadmin_proto_rawDescGZIP(), []int{1}
}

func (x *PromoteRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// PromoteResponse confirms the promotion
type PromoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *PromoteResponse) Reset() {
	*x = PromoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_haadmin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteResponse) ProtoMessage() {}

func (x *PromoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_haadmin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteResponse.ProtoReflect.Descriptor instead.
func (*PromoteResponse) Descriptor() ([]byte, []int) {
	return file_haadmin_proto_rawDescGZIP(), []int{2}
}

func (x *PromoteResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// DemoteRequest asks the principal to become a REPLICA
type DemoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DemoteRequest) Reset() {
	*x = DemoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_haadmin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteRequest) ProtoMessage() {}

func (x *DemoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_haadmin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteRequest.ProtoReflect.Descriptor instead.
func (*DemoteRequest) Descriptor() ([]byte, []int) {
	return file_haadmin_proto_rawDescGZIP(), []int{3}
}

// DemoteResponse confirms the demotion
type DemoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *DemoteResponse) Reset() {
	*x = DemoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_haadmin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteResponse) ProtoMessage() {}

func (x *DemoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_haadmin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteResponse.ProtoReflect.Descriptor instead.
func (*DemoteResponse) Descriptor() ([]byte, []int) {
	return file_haadmin_proto_rawDescGZIP(), []int{4}
}

func (x *DemoteResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// StatusRequest is empty — just fetches current state
type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_haadmin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_haadmin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_haadmin_proto_rawDescGZIP(), []int{5}
}

var File_haadmin_proto protoreflect.FileDescriptor

var file_haadmin_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x22, 0xf0, 0x02, 0x0a, 0x10,
	0x48, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x65, 0x65, 0x72, 0x52, 0x65,
	0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x4e, 0x75, 0x6d, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x26,
	0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0xd1, 0x01, 0x0a, 0x07, 0x48, 0x41,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x19, 0x2e, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x68, 0x61, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69,
	0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06,
	0x44, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3f, 0x5a,
	0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x67, 0x6f,
	0x70, 0x72, 0x6f, 0x6a, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x61, 0x72, 0x67, 0x6f, 0x63, 0x64,
	0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x68, 0x61, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_haadmin_proto_rawDescOnce sync.Once
	file_haadmin_proto_rawDescData = file_haadmin_proto_rawDesc
)

func file_haadmin_proto_rawDescGZIP() []byte {
	file_haadmin_proto_rawDescOnce.Do(func() {
		file_haadmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_haadmin_proto_rawDescData)
	})
	return file_haadmin_proto_rawDescData
}

var file_haadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_haadmin_proto_goTypes = []interface{}{
	(*HAStatusResponse)(nil), // 0: haadminapi.HAStatusResponse
	(*PromoteRequest)(nil),   // 1: haadminapi.PromoteRequest
	(*PromoteResponse)(nil),  // 2: haadminapi.PromoteResponse
	(*DemoteRequest)(nil),    // 3: haadminapi.DemoteRequest
	(*DemoteResponse)(nil),   // 4: haadminapi.DemoteResponse
	(*StatusRequest)(nil),    // 5: haadminapi.StatusRequest
}
var file_haadmin_proto_depIdxs = []int32{
	5, // 0: haadminapi.HAAdmin.Status:input_type -> haadminapi.StatusRequest
	1, // 1: haadminapi.HAAdmin.Promote:input_type -> haadminapi.PromoteRequest
	3, // 2: haadminapi.HAAdmin.Demote:input_type -> haadminapi.DemoteRequest
	0, // 3: haadminapi.HAAdmin.Status:output_type -> haadminapi.HAStatusResponse
	2, // 4: haadminapi.HAAdmin.Promote:output_type -> haadminapi.PromoteResponse
	4, // 5: haadminapi.HAAdmin.Demote:output_type -> haadminapi.DemoteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_haadmin_proto_init() }
func file_haadmin_proto_init() {
	if File_haadmin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_haadmin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HAStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_haadmin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_haadmin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_haadmin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_haadmin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_haadmin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_haadmin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_haadmin_proto_goTypes,
		DependencyIndexes: file_haadmin_proto_depIdxs,
		MessageInfos:      file_haadmin_proto_msgTypes,
	}.Build()
	File_haadmin_proto = out.File
	file_haadmin_proto_rawDesc = nil
	file_haadmin_proto_goTypes = nil
	file_haadmin_proto_depIdxs = nil
}
