// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: logstream.proto

package logstreamapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogStreamData represents a line (or chunk) of log data sent from the agent
type LogStreamData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier matching the original request/event UUID
	RequestUuid string `protobuf:"bytes,1,opt,name=request_uuid,json=requestUuid,proto3" json:"request_uuid,omitempty"`
	// Log data content. Recommended to be a single line including trailing newline
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// End of stream indicator
	Eof bool `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	// Optional error message
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamData) Reset() {
	*x = LogStreamData{}
	mi := &file_logstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamData) ProtoMessage() {}

func (x *LogStreamData) ProtoReflect() protoreflect.Message {
	mi := &file_logstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamData.ProtoReflect.Descriptor instead.
func (*LogStreamData) Descriptor() ([]byte, []int) {
	return file_logstream_proto_rawDescGZIP(), []int{0}
}

func (x *LogStreamData) GetRequestUuid() string {
	if x != nil {
		return x.RequestUuid
	}
	return ""
}

func (x *LogStreamData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LogStreamData) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *LogStreamData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LogStreamResponse is returned by principal when the agent closes the stream
type LogStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestUuid   string                 `protobuf:"bytes,1,opt,name=request_uuid,json=requestUuid,proto3" json:"request_uuid,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 200 on success
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LinesReceived int32                  `protobuf:"varint,4,opt,name=lines_received,json=linesReceived,proto3" json:"lines_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_logstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_logstream_proto_rawDescGZIP(), []int{1}
}

func (x *LogStreamResponse) GetRequestUuid() string {
	if x != nil {
		return x.RequestUuid
	}
	return ""
}

func (x *LogStreamResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LogStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogStreamResponse) GetLinesReceived() int32 {
	if x != nil {
		return x.LinesReceived
	}
	return 0
}

var File_logstream_proto protoreflect.FileDescriptor

const file_logstream_proto_rawDesc = "" +
	"\n" +
	"\x0flogstream.proto\x12\flogstreamapi\"n\n" +
	"\rLogStreamData\x12!\n" +
	"\frequest_uuid\x18\x01 \x01(\tR\vrequestUuid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8b\x01\n" +
	"\x11LogStreamResponse\x12!\n" +
	"\frequest_uuid\x18\x01 \x01(\tR\vrequestUuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12%\n" +
	"\x0elines_received\x18\x04 \x01(\x05R\rlinesReceived2`\n" +
	"\x10LogStreamService\x12L\n" +
	"\n" +
	"StreamLogs\x12\x1b.logstreamapi.LogStreamData\x1a\x1f.logstreamapi.LogStreamResponse(\x01BAZ?github.com/argoproj-labs/argocd-agent/pkg/api/grpc/logstreamapib\x06proto3"

var (
	file_logstream_proto_rawDescOnce sync.Once
	file_logstream_proto_rawDescData []byte
)

func file_logstream_proto_rawDescGZIP() []byte {
	file_logstream_proto_rawDescOnce.Do(func() {
		file_logstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logstream_proto_rawDesc), len(file_logstream_proto_rawDesc)))
	})
	return file_logstream_proto_rawDescData
}

var file_logstream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logstream_proto_goTypes = []any{
	(*LogStreamData)(nil),     // 0: logstreamapi.LogStreamData
	(*LogStreamResponse)(nil), // 1: logstreamapi.LogStreamResponse
}
var file_logstream_proto_depIdxs = []int32{
	0, // 0: logstreamapi.LogStreamService.StreamLogs:input_type -> logstreamapi.LogStreamData
	1, // 1: logstreamapi.LogStreamService.StreamLogs:output_type -> logstreamapi.LogStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logstream_proto_init() }
func file_logstream_proto_init() {
	if File_logstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logstream_proto_rawDesc), len(file_logstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logstream_proto_goTypes,
		DependencyIndexes: file_logstream_proto_depIdxs,
		MessageInfos:      file_logstream_proto_msgTypes,
	}.Build()
	File_logstream_proto = out.File
	file_logstream_proto_goTypes = nil
	file_logstream_proto_depIdxs = nil
}
